Opetushallitus/valintojen-toteuttaminen

- tests/e2e/perustiedot.spec.ts
Oletko lisännyt tarvittavat yksikkö- tai ui-testit toiminnallisuudelle? Kyllä/En
Oletko tarkistanut ja päivittänyt riippuvuudet? Kyllä/En
Oletko kokeillut toimiiko käyttöliittymä mobiilissa landscape moodissa? Kyllä/En/Ei koske
> Add missing await

- src/app/hooks/useUserPermissions.ts
- src/app/layout.tsx
- src/app/lib/http-client.ts
- src/app/localization-provider.tsx
- src/app/permission-provider.tsx
Oletko lisännyt tarvittavat yksikkö- tai ui-testit toiminnallisuudelle? Kyllä/En
Oletko tarkistanut ja päivittänyt riippuvuudet? Kyllä/En
Oletko kokeillut toimiiko käyttöliittymä mobiilissa landscape moodissa? Kyllä/En/Ei koske
> Use error view instead of error boundary

- README.md
- pull_request_template.md
- src/app/haku/[oid]/hakukohde-list.tsx
- src/app/haku/[oid]/hakukohde-panel.tsx
- src/app/haku/[oid]/hakukohde-search.tsx
- src/app/haku/[oid]/layout.tsx
- src/app/haku/[oid]/page.tsx
- src/app/hooks/useHakukohdeSearch.ts
- src/app/lokalisaatio/fi.json
- tests/e2e/haku.spec.ts
> Ok 498 hakukohteen suodattimet

- src/app/(root)/page.tsx
- src/app/components/external-link.tsx
- src/app/components/table/list-table.tsx
- src/app/components/table/table-pagination-wrapper.tsx
- src/app/haku/[oid]/hakukohde-panel.tsx
- src/app/haku/[oid]/hakukohde-search.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/TabContainer.ts
- src/app/haku/[oid]/hakukohde/[hakukohde]/hakeneet/hakeneet-search.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/hakeneet/hakeneet-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/hakeneet/page.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/hakukohde-tabs.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/perustiedot/loading.tsx
- src/app/hooks/useHakeneetSearch.ts
- src/app/lib/ataru.ts
- src/app/lib/configuration.ts
- src/app/lib/http-client.ts
- src/app/lib/kouta.ts
- src/app/lokalisaatio/fi.json
- tests/e2e/fixtures/hakeneet.json
- tests/e2e/hakeneet.spec.ts
- tests/e2e/haku.spec.ts
- tests/e2e/hakukohde.spec.ts
- tests/e2e/playwright.setup.js
> Ok 502 hakeneet

- src/app/hooks/useLasketutValinnanVaiheet.ts
- src/app/lib/configuration.ts
- src/app/lib/http-client.ts
- src/app/lib/valintalaskenta-service.ts
- src/app/theme.tsx
Oletko lisännyt tarvittavat yksikkö- tai ui-testit toiminnallisuudelle? En
> OK-513: Lisätty valintalaskenta-service

- .github/workflows/build.yml
- next.config.mjs
- package.json
- src/app/hooks/useHakukohdeSearch.ts
- src/app/lib/checkAccessibility.ts
- src/app/lib/configuration.ts
- src/app/lokalisaatio/route.ts
Oletko lisännyt tarvittavat yksikkö- tai ui-testit toiminnallisuudelle? En
> Testiajon optimointia CI:ssä

- src/app/(root)/@controls/page.tsx
- src/app/components/oph-form-control.tsx
- src/app/components/oph-select.tsx
- src/app/components/table/page-size-selector.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/hakeneet/hakeneet-search.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/hakijaryhmat/hakijaryhmat-controls.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/hakijaryhmat/hakijaryhmat-search.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/valintalaskennan-tulos/valintalaskennan-tulos-search.tsx
- src/app/lib/common.ts
- src/app/theme.tsx
Oletko lisännyt tarvittavat yksikkö- tai ui-testit toiminnallisuudelle? En. (Lisätään yksikkötestit kun rajapinta hioutuu ja on valmis siirrettäväksi oph-design-system:iin)
Oletko testannut että lisäämäsi toiminto on saavutettava? Kyllä (Entiset testit testaa myös tätä).
> Lisätty OphFormControl ja otettu käyttöön

- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/change-history-modal.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/other-actions-cell.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/sijoittelun-tulos-content.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/sijoittelun-tulos-form.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/sijoittelun-tulos-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/page.tsx
- src/app/lib/configuration.ts
- src/app/lib/hakukohde-tab-utils.test.ts
- src/app/lib/kouta.test.ts
- src/app/lib/kouta.ts
- src/app/lib/state/laskenta-state.test.ts
- src/app/lib/types/kouta-types.ts
- src/app/lib/types/sijoittelu-types.ts
- src/app/lib/types/valinta-tulos-types.ts
- src/app/lib/valinta-tulos-service.ts
- src/app/lib/valintalaskentakoostepalvelu.ts
- src/app/lokalisaatio/fi.json
- tests/e2e/fixtures/hakukohteet.json
- tests/e2e/sijoittelun-tulokset.spec.ts
Oletko tarkistanut ja päivittänyt riippuvuudet? Kyllä
> Ok 580 muut

- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/sijoittelun-tulos-actions.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/sijoittelun-tulos-content.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/sijoittelun-tulos-form.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/sijoittelun-tulos-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/vastaanotto-cell.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/page.tsx
- src/app/haku/[oid]/henkilo/[hakemusOid]/components/hakutoive-accordion-content.tsx
- src/app/haku/[oid]/henkilo/[hakemusOid]/components/hakutoive-accordion.tsx
- src/app/haku/[oid]/henkilo/[hakemusOid]/components/hakutoiveet-table.tsx
- src/app/haku/[oid]/henkilo/[hakemusOid]/components/valinnan-tilat-edit-modal.tsx
- src/app/haku/[oid]/henkilo/[hakemusOid]/components/valinnan-tulos-cells.tsx
- src/app/hooks/useHaunAsetukset.tsx
- src/app/hooks/useIsHakuPublishAllowed.ts
- src/app/lib/sijoittelun-tulokset-utils.ts
- src/app/lokalisaatio/fi.json
- tests/e2e/henkilo.spec.ts
- tests/e2e/valintalaskennan-tulokset.spec.ts
Oletko testannut että lisäämäsi toiminto on saavutettava? En
> OK-776: Julkaistavissa-tilan muokkaaminen henkilö-näkymässä

- tests/e2e/hakeneet.spec.ts
- tests/e2e/hakijaryhmat.spec.ts
- tests/e2e/haku.spec.ts
- tests/e2e/hakukohde-tabs.spec.ts
- tests/e2e/harkinnanvaraiset.spec.ts
- tests/e2e/haut.spec.ts
- tests/e2e/index.spec.ts
- tests/e2e/lokalisointi.spec.ts
- tests/e2e/permissions.spec.ts
- tests/e2e/perustiedot.spec.ts
- tests/e2e/pistesyotto.spec.ts
- tests/e2e/sijoittelun-tulokset.spec.ts
- tests/e2e/valinnan-hallinta.spec.ts
- tests/e2e/valintakoekutsut.spec.ts
- tests/e2e/valintalaskennan-tulokset-ilman-laskentaa.spec.ts
- tests/e2e/valintalaskennan-tulokset.spec.ts
- tests/e2e/valintaryhmittain.spec.ts
> Rename playwright tests

- LICENSE.md
Oletko lisännyt tarvittavat yksikkö- tai ui-testit toiminnallisuudelle? Ei koske
> OY-5093 update license

- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/sijoittelun-tulos-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/vastaanotto-cell.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/hooks/useHakijanVastaanottotila.ts
- src/app/lokalisaatio/fi.json
- src/lib/configuration.ts
- src/lib/valinta-tulos-service/valinta-tulos-service.ts
- src/lib/valinta-tulos-service/valinta-tulos-types.ts
- tests/e2e/fixtures/valintatapajonon-hakijoiden-vastaanottotila.json
- tests/e2e/playwright.setup.ts
- tests/e2e/sijoittelun-tulokset.spec.ts
> Hakijalle näytettävä vastaanottotila

- src/app/haku/[oid]/hakukohde/[hakukohde]/hakeneet/components/hakeneet-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/hakijaryhmat/components/hakijaryhma-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/harkinnanvaraiset/components/harkinnanvaraiset-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/valintakoekutsut/components/valintakoekutsut-hakijoittain-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/valintakoekutsut/components/valintakoekutsut-kokeittain-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/valintalaskennan-tulokset/components/laskennaton-valintatapajono-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/valintalaskennan-tulokset/components/laskettu-valintatapajono-table.tsx
- src/components/table/table-columns.test.ts
- src/components/table/table-columns.tsx
> Hakijakolumnin sisältä osoittaa oletuksena hakemukseen

- src/app/haku/[oid]/hakukohde/[hakukohde]/hakeneet/components/hakeneet-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/hakijaryhmat/components/hakijaryhma-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/harkinnanvaraiset/components/harkinnanvaraiset-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/pistesyotto/components/pistesyotto-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/sijoittelun-tulos-table.tsx
- src/components/table/table-columns.tsx
Oletko lisännyt tarvittavat yksikkö- tai ui-testit toiminnallisuudelle? En
> Fix some hakija columns not sorting properly

- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/letter-template-modal.tsx
- src/app/haku/[oid]/yhteisvalinnan-hallinta/page.tsx
- src/app/haku/[oid]/yhteisvalinnan-hallinta/sijoittelu/components/sijoittelu-actions.tsx
- src/app/haku/[oid]/yhteisvalinnan-hallinta/sijoittelu/components/sijoittelu-basic-info.tsx
- src/app/haku/[oid]/yhteisvalinnan-hallinta/sijoittelu/components/sijoittelu-container.tsx
- src/app/haku/[oid]/yhteisvalinnan-hallinta/sijoittelu/components/sijoittelu-info.tsx
- src/app/haku/[oid]/yhteisvalinnan-hallinta/sijoittelu/components/sijoittelu-schedule.tsx
- src/components/calendar-component.tsx
- src/components/file-download-button.tsx
- src/hooks/useToaster.ts
- src/lib/configuration.ts
- src/lib/hakukohde-tab-utils.ts
- src/lib/kouta/kouta-service.ts
- src/lib/localization/messages/fi.json
- src/lib/sijoittelu/sijoittelu-service.ts
- src/lib/state/laskenta-state.ts
- src/lib/types/sijoittelu-types.ts
- src/lib/valinta-tulos-service/valinta-tulos-service.ts
- src/lib/valinta-tulos-service/valinta-tulos-types.ts
- src/lib/valintalaskentakoostepalvelu/valintalaskentakoostepalvelu-service.ts
- tests/e2e/playwright.setup.ts
- tests/e2e/yhteisvalinnan-hallinta.spec.ts
> Ok sijoittelu

- src/app/haku/[oid]/hakukohde/[hakukohde]/pistesyotto/components/pistesyotto-form.tsx
- src/app/haku/[oid]/henkilo/[hakemusOid]/components/henkilon-pistesyotto.tsx
- src/components/koe-inputs.tsx
- src/lib/localization/messages/fi.json
- src/lib/state/pistesyotto-state.test.ts
- src/lib/state/pistesyotto-state.ts
- tests/e2e/fixtures/pistetiedot.json
- tests/e2e/pistesyotto.spec.ts
> Fix pistesyotto max

- src/app/haku/[oid]/hakukohde/[hakukohde]/valintalaskennan-tulokset/components/sijoittelu-status-change-button.test.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/valintalaskennan-tulokset/components/sijoittelu-status-change-button.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/valintalaskennan-tulokset/hooks/useSijoitteluStatusMutation.tsx
- src/components/ValinnanTuloksetActions.tsx
- src/lib/configuration/configuration.ts
- src/lib/configuration/server-configuration.ts
- src/lib/valintalaskenta/valintalaskenta-service.ts
- src/lib/valintaperusteet/valintaperusteet-service.ts
Oletko lisännyt tarvittavat yksikkö- tai ui-testit toiminnallisuudelle? En
> Salli hyväksy ja julkaise valintaesitys valinnan tulokset välilehdellä

- src/lib/valintalaskentakoostepalvelu/valintalaskentakoostepalvelu-service.ts
- tests/e2e/pistesyotto.spec.ts
Oletko tarkistanut ja päivittänyt riippuvuudet? Kyllä
> Sort koe columns by description

- src/app/haku/[oid]/hakukohde/components/hakukohde-panel.tsx
- src/app/haku/[oid]/hakukohde/components/hakukohde-search-controls.tsx
- src/app/haku/[oid]/hakukohde/components/hakukohde-search-input.tsx
- src/components/collapsible.tsx
- src/components/hakukohde-tab-link.tsx
- src/hooks/useHakukohdeSearch.ts
- src/lib/configuration/server-configuration.ts
- src/lib/localization/messages/fi.json
- src/lib/valintalaskentakoostepalvelu/valintalaskentakoostepalvelu-service.ts
- tests/e2e/haku.spec.ts
- tests/e2e/playwright.setup.ts
> OK-561: Hakukohteiden "on valintakoe"-suodatus

- src/app/haku/[oid]/hakukohde/components/hakukohde-search-controls.tsx
- src/hooks/useHakukohdeSearch.test.ts
- src/hooks/useHakukohdeSearch.ts
- src/lib/localization/messages/fi.json
- src/lib/valintalaskentakoostepalvelu/valintalaskentakoostepalvelu-service.ts
- src/lib/valintalaskentakoostepalvelu/valintalaskentakoostepalvelu-types.ts
- tests/e2e/fixtures/valintatiedot-hakukohteittain.json
- tests/e2e/haku.spec.ts
Oletko tarkistanut ja päivittänyt riippuvuudet? Kyllä
> Julkaisematta ja sijoittelematta hakukohde suodattimet

- package-lock.json
- package.json
- src/app/haku/[oid]/hakukohde/components/hakukohde-panel.tsx
- src/app/haku/[oid]/hakukohde/components/hakukohde-search-controls.tsx
- src/hooks/useHakukohdeSearch.test.ts
- src/hooks/useHakukohdeSearch.ts
- src/lib/koodisto/koodisto-service.ts
- src/lib/koodisto/useKoulutustyypit.ts
- src/lib/kouta/kouta-service.ts
- src/lib/kouta/kouta-types.ts
- src/lib/localization/messages/fi.json
- tests/e2e/fixtures/hakukohteet.json
- tests/e2e/fixtures/koulutustyypit.json
- tests/e2e/haku.spec.ts
- tests/e2e/playwright.setup.ts
Oletko tarkistanut ja päivittänyt riippuvuudet? Kyllä
> Ok 990 koulutustyyppi rajaimet

- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/components/sijoittelun-tulos-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/valinnan-tulokset/components/ValinnanTuloksetTable.tsx
- src/components/ValinnanTilaCell.test.tsx
- src/components/ValinnanTilaCell.tsx
- src/components/table/table-columns.tsx
- src/lib/permissions.test.ts
- src/lib/valintalaskentakoostepalvelu/valintalaskentakoostepalvelu-service.ts
Oletko lisännyt tarvittavat yksikkö- tai ui-testit toiminnallisuudelle? Kyllä (Olemassaolevaa testiä muokattu)
> OK-1007: Käyttöoikeustarkistusten korjauksia

- src/app/haku/[oid]/hakukohde/[hakukohde]/pistesyotto/components/koe-inputs.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/pistesyotto/components/pistesyotto-form.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/pistesyotto/components/pistesyotto-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/pistesyotto/lib/hakukohde-pistesyotto-state.test.ts
- src/app/haku/[oid]/hakukohde/[hakukohde]/pistesyotto/lib/hakukohde-pistesyotto-state.ts
- src/app/haku/[oid]/hakukohde/[hakukohde]/pistesyotto/page.tsx
- src/app/haku/[oid]/henkilo/[hakemusOid]/components/henkilon-pistesyotto.tsx
- src/app/haku/[oid]/henkilo/[hakemusOid]/components/kokeen-pistesyotto.tsx
- src/app/haku/[oid]/henkilo/[hakemusOid]/hooks/useHenkiloPageData.ts
- src/app/haku/[oid]/henkilo/[hakemusOid]/lib/henkilon-pistesyotto-state.test.ts
- src/app/haku/[oid]/henkilo/[hakemusOid]/lib/henkilon-pistesyotto-state.ts
- src/app/haku/[oid]/henkilo/[hakemusOid]/page.tsx
- src/components/koe-inputs-stateless.test.tsx
- src/components/koe-inputs-stateless.tsx
- src/components/toaster.tsx
- src/lib/common.ts
- src/lib/localization/messages/fi.json
- src/lib/state/pistesyotto-state-common.ts
- src/lib/state/pistesyotto-state.test.ts
- src/lib/state/pistesyotto-state.ts
- src/lib/types/laskenta-types.ts
- src/lib/valintalaskentakoostepalvelu/valintalaskentakoostepalvelu-service.ts
- tests/e2e/henkilo.spec.ts
> Ok 1004 henkilot one save button per hakukohde

- src/app/haku/[oid]/hakukohde/[hakukohde]/hakijaryhmat/hooks/useHakijaryhmatSearch.ts
- src/app/haku/[oid]/hakukohde/[hakukohde]/sijoittelun-tulokset/hooks/useSijoittelunTulosSearch.ts
- src/app/haku/[oid]/hakukohde/[hakukohde]/valinnan-tulokset/hooks/useValinnanTuloksetSearch.ts
- src/app/haku/[oid]/hakukohde/[hakukohde]/valintalaskennan-tulokset/components/laskennaton-valintatapajono-content.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/valintalaskennan-tulokset/components/laskennaton-valintatapajono-table.tsx
- src/app/haku/[oid]/hakukohde/[hakukohde]/valintalaskennan-tulokset/page.tsx
- src/components/table/table-utils.test.ts
- src/components/table/table-utils.ts
- src/hooks/useEditableValintalaskennanTulokset.ts
- src/hooks/useHasChanged.test.tsx
- src/hooks/useHasChanged.tsx
- src/lib/sortBySijoittelunTila.ts
- src/lib/sortByValinnanTila.test.ts
- src/lib/sortByValinnanTila.ts
- src/lib/state/jono-tulos-state.test.ts
- src/lib/state/jono-tulos-state.ts
- tests/e2e/sijoittelun-tulokset.spec.ts
> Ok 1022 valinnan tilan perusteella sort fix

- src/app/haku/[oid]/hakukohde/[hakukohde]/perustiedot/components/valintatapajonot-table.tsx
- src/lib/localization/messages/fi.json
- src/lib/types/sijoittelu-types.ts
- src/lib/valinta-tulos-service/valinta-tulos-service.ts
- tests/e2e/perustiedot.spec.ts
> Näytä ehdollisesti paikan vastaanottaneet korkeakouluhaussa

- .github/workflows/deploy.yml
- cdk/bin/valintojen-toteuttaminen.ts
- cdk/cdk.json
- cdk/lib/certificate-stack.ts
- cdk/lib/constants.ts
- cdk/lib/hosted-zone-stack.ts
- cdk/lib/sovellus-stack.ts
- deploy.sh
Oletko lisännyt tarvittavat yksikkö- tai ui-testit toiminnallisuudelle? Ei koske
> Ok 546 production

- src/app/haku/[oid]/components/haku-tabs.tsx
- src/app/haku/[oid]/valintaryhma/[valintaryhma]/components/valintaryhma-content.tsx
- src/app/haku/[oid]/valintaryhma/components/valintaryhma-link.tsx
- src/app/haku/[oid]/valintaryhma/components/valintaryhma-list.tsx
- src/app/haku/[oid]/valintaryhma/hooks/useValintaryhmaSearch.ts
- src/app/haku/[oid]/valintaryhma/lib/valintaryhma-util.ts
- src/lib/configuration/server-configuration.ts
- src/lib/permissions.ts
- src/lib/valintaperusteet/valintaperusteet-service.test.ts
- src/lib/valintaperusteet/valintaperusteet-service.ts
- src/lib/valintaperusteet/valintaperusteet-types.ts
- tests/e2e/fixtures/valintaryhma-puu.json
- tests/e2e/valintaryhmittain.spec.ts
Lisätty/päivitetty myös käyttöoikeustarkistuksia valintaryhmille.
> Ok 861 valintaryhmat support for hakukohde without haku linkage
